server:
  port: 80
spring:
  datasource:
    url: jdbc:h2:mem:hellomapstruct;
    driver-class-name: org.h2.Driver
    username: abc
    password: abc
  h2:
    console:
      enabled: true
      path: /h2

